# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(235, 235, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget.setStyleSheet("background-color: rgb(230, 236, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_window_in_stacked_widget = QtWidgets.QWidget()
        self.main_window_in_stacked_widget.setObjectName("main_window_in_stacked_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_window_in_stacked_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_book_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.add_book_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.add_book_button.setObjectName("add_book_button")
        self.horizontalLayout_2.addWidget(self.add_book_button)
        self.search_book_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.search_book_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.search_book_button.setObjectName("search_book_button")
        self.horizontalLayout_2.addWidget(self.search_book_button)
        self.add_category_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.add_category_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.add_category_button.setObjectName("add_category_button")
        self.horizontalLayout_2.addWidget(self.add_category_button)
        self.delete_category_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.delete_category_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.delete_category_button.setObjectName("delete_category_button")
        self.horizontalLayout_2.addWidget(self.delete_category_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.treeWidget = QtWidgets.QTreeWidget(self.main_window_in_stacked_widget)
        self.treeWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.treeWidget.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Категории")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout_24.addWidget(self.treeWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.main_window_in_stacked_widget)
        self.listWidget.setMinimumSize(QtCore.QSize(900, 0))
        self.listWidget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(99, 47, 255);")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.main_window_in_stacked_widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(600, 0))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.pushButton.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_24.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_window_in_stacked_widget)
        self.add_book_window_in_stacked_widget = QtWidgets.QWidget()
        self.add_book_window_in_stacked_widget.setObjectName("add_book_window_in_stacked_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.add_book_window_in_stacked_widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.back_to_main_window_add_book = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.back_to_main_window_add_book.setMaximumSize(QtCore.QSize(150, 16777215))
        self.back_to_main_window_add_book.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_add_book.setObjectName("back_to_main_window_add_book")
        self.gridLayout_5.addWidget(self.back_to_main_window_add_book, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.label_7 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_8.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.pushButton_2.setBaseSize(QtCore.QSize(150, 0))
        self.pushButton_2.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 35 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 5px;\n"
"padding: 3px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.add_book_window_in_stacked_widget)
        self.treeWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.horizontalLayout_7.addWidget(self.treeWidget_2)
        self.label_9 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.pushButton_3 = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.pushButton_3.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 1, 3, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 2, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 2, 2)
        self.stackedWidget.addWidget(self.add_book_window_in_stacked_widget)
        self.edit_window_in_stacked_widget = QtWidgets.QWidget()
        self.edit_window_in_stacked_widget.setObjectName("edit_window_in_stacked_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.edit_window_in_stacked_widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.back_to_main_window_edit_book = QtWidgets.QPushButton(self.edit_window_in_stacked_widget)
        self.back_to_main_window_edit_book.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_edit_book.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_edit_book.setObjectName("back_to_main_window_edit_book")
        self.gridLayout_7.addWidget(self.back_to_main_window_edit_book, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem9, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        self.label_2 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_10.addWidget(self.lineEdit_7)
        self.label_10 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_11.addWidget(self.lineEdit_8)
        self.label_11 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.edit_window_in_stacked_widget)
        self.treeWidget_3.setMinimumSize(QtCore.QSize(450, 0))
        self.treeWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.treeWidget_3.headerItem().setText(0, "1")
        self.horizontalLayout_12.addWidget(self.treeWidget_3)
        self.label_12 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_12.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.pushButton_4 = QtWidgets.QPushButton(self.edit_window_in_stacked_widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_4.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_13.addWidget(self.pushButton_4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 1, 2, 2, 1)
        spacerItem12 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.edit_window_in_stacked_widget)
        self.delete_window_in_stacked_widget = QtWidgets.QWidget()
        self.delete_window_in_stacked_widget.setObjectName("delete_window_in_stacked_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.delete_window_in_stacked_widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.back_to_main_window_search_bok = QtWidgets.QPushButton(self.delete_window_in_stacked_widget)
        self.back_to_main_window_search_bok.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_search_bok.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_search_bok.setObjectName("back_to_main_window_search_bok")
        self.gridLayout_8.addWidget(self.back_to_main_window_search_bok, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem14, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_14.addWidget(self.lineEdit_9)
        self.label_3 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_15.addWidget(self.lineEdit_10)
        self.label_13 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_13.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_16.addWidget(self.lineEdit_11)
        self.label_14 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_14.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.delete_window_in_stacked_widget)
        self.treeWidget_4.setMinimumSize(QtCore.QSize(450, 0))
        self.treeWidget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_4.setObjectName("treeWidget_4")
        self.treeWidget_4.headerItem().setText(0, "1")
        self.horizontalLayout_17.addWidget(self.treeWidget_4)
        self.label_15 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_15.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem15)
        self.pushButton_5 = QtWidgets.QPushButton(self.delete_window_in_stacked_widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_5.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_18.addWidget(self.pushButton_5)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 1, 2, 2, 1)
        spacerItem17 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem17, 2, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem18, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.delete_window_in_stacked_widget)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.back_to_main_window_delete_category = QtWidgets.QPushButton(self.page)
        self.back_to_main_window_delete_category.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_delete_category.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_delete_category.setObjectName("back_to_main_window_delete_category")
        self.gridLayout_10.addWidget(self.back_to_main_window_delete_category, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem19, 1, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.treeWidget_5 = QtWidgets.QTreeWidget(self.page)
        self.treeWidget_5.setMinimumSize(QtCore.QSize(450, 0))
        self.treeWidget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_5.setObjectName("treeWidget_5")
        self.treeWidget_5.headerItem().setText(0, "1")
        self.horizontalLayout_22.addWidget(self.treeWidget_5)
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem20)
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_8.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_23.addWidget(self.pushButton_8)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem21)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.gridLayout_10.addLayout(self.verticalLayout_7, 1, 2, 2, 1)
        spacerItem22 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem22, 2, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem23, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.search_window_in_stacked_widget = QtWidgets.QWidget()
        self.search_window_in_stacked_widget.setObjectName("search_window_in_stacked_widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.search_window_in_stacked_widget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.back_to_main_window_add_category = QtWidgets.QPushButton(self.search_window_in_stacked_widget)
        self.back_to_main_window_add_category.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_add_category.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_add_category.setObjectName("back_to_main_window_add_category")
        self.gridLayout_9.addWidget(self.back_to_main_window_add_category, 0, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem24, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.search_window_in_stacked_widget)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_20.addWidget(self.lineEdit_12)
        self.label_4 = QtWidgets.QLabel(self.search_window_in_stacked_widget)
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_20.addWidget(self.label_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.treeView = QtWidgets.QTreeView(self.search_window_in_stacked_widget)
        self.treeView.setMinimumSize(QtCore.QSize(450, 0))
        self.treeView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_21.addWidget(self.treeView)
        self.label_16 = QtWidgets.QLabel(self.search_window_in_stacked_widget)
        self.label_16.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_21.addWidget(self.label_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem25)
        self.pushButton_6 = QtWidgets.QPushButton(self.search_window_in_stacked_widget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_6.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_19.addWidget(self.pushButton_6)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem26)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.gridLayout_9.addLayout(self.verticalLayout_6, 1, 2, 2, 1)
        spacerItem27 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem27, 2, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem28, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.search_window_in_stacked_widget)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1347, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_book_button.setText(_translate("MainWindow", "Добавить книгу"))
        self.search_book_button.setText(_translate("MainWindow", "Найти книгу"))
        self.add_category_button.setText(_translate("MainWindow", "Добавить категорию"))
        self.delete_category_button.setText(_translate("MainWindow", "Удалить категорию"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Книги"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Стандартные"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Жанры"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Антиутопии"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Фантастика"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Авторы"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Год"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Пользовательские"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Применить"))
        self.back_to_main_window_add_book.setText(_translate("MainWindow", "На главную"))
        self.label_5.setText(_translate("MainWindow", "Название"))
        self.label_6.setText(_translate("MainWindow", "Год"))
        self.label_7.setText(_translate("MainWindow", "Автор"))
        self.label_8.setText(_translate("MainWindow", "Путь"))
        self.pushButton_2.setText(_translate("MainWindow", "Выбрать путь"))
        self.label_9.setText(_translate("MainWindow", "Каегории"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.back_to_main_window_edit_book.setText(_translate("MainWindow", "На главную"))
        self.label_2.setText(_translate("MainWindow", "Название"))
        self.label_10.setText(_translate("MainWindow", "Автор"))
        self.label_11.setText(_translate("MainWindow", "Год"))
        self.label_12.setText(_translate("MainWindow", "Категории"))
        self.pushButton_4.setText(_translate("MainWindow", "Изменить"))
        self.back_to_main_window_search_bok.setText(_translate("MainWindow", "На главную"))
        self.label_3.setText(_translate("MainWindow", "Название"))
        self.label_13.setText(_translate("MainWindow", "Автор"))
        self.label_14.setText(_translate("MainWindow", "Год"))
        self.label_15.setText(_translate("MainWindow", "Катогории"))
        self.pushButton_5.setText(_translate("MainWindow", "Найти"))
        self.back_to_main_window_delete_category.setText(_translate("MainWindow", "На главную"))
        self.label_17.setText(_translate("MainWindow", "Категории"))
        self.pushButton_8.setText(_translate("MainWindow", "Удалить"))
        self.back_to_main_window_add_category.setText(_translate("MainWindow", "На главную"))
        self.label_4.setText(_translate("MainWindow", "Название категориии"))
        self.label_16.setText(_translate("MainWindow", "Категории"))
        self.pushButton_6.setText(_translate("MainWindow", "Добавить категорию"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Приложение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Статистика"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Документация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
