# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1685, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(235, 235, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget.setStyleSheet("background-color: rgb(230, 236, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_window_in_stacked_widget = QtWidgets.QWidget()
        self.main_window_in_stacked_widget.setObjectName("main_window_in_stacked_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_window_in_stacked_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_book_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.add_book_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.add_book_button.setObjectName("add_book_button")
        self.horizontalLayout_2.addWidget(self.add_book_button)
        self.search_book_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.search_book_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.search_book_button.setObjectName("search_book_button")
        self.horizontalLayout_2.addWidget(self.search_book_button)
        self.add_category_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.add_category_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.add_category_button.setObjectName("add_category_button")
        self.horizontalLayout_2.addWidget(self.add_category_button)
        self.delete_category_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.delete_category_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.delete_category_button.setObjectName("delete_category_button")
        self.horizontalLayout_2.addWidget(self.delete_category_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.main_window_tags = QtWidgets.QTreeWidget(self.main_window_in_stacked_widget)
        self.main_window_tags.setMinimumSize(QtCore.QSize(500, 0))
        self.main_window_tags.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"")
        self.main_window_tags.setObjectName("main_window_tags")
        self.main_window_tags.headerItem().setText(0, "Категории")
        item_0 = QtWidgets.QTreeWidgetItem(self.main_window_tags)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.main_window_tags)
        self.horizontalLayout_24.addWidget(self.main_window_tags)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.main_window_in_stacked_widget)
        self.listWidget.setMinimumSize(QtCore.QSize(900, 0))
        self.listWidget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(116, 106, 255);\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_window_LineEdit = QtWidgets.QLineEdit(self.main_window_in_stacked_widget)
        self.main_window_LineEdit.setMinimumSize(QtCore.QSize(600, 0))
        self.main_window_LineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border: 4px solid rgb(116, 106, 255);")
        self.main_window_LineEdit.setObjectName("main_window_LineEdit")
        self.horizontalLayout.addWidget(self.main_window_LineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.main_window_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.main_window_button.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.main_window_button.setObjectName("main_window_button")
        self.horizontalLayout.addWidget(self.main_window_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_24.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_window_in_stacked_widget)
        self.add_book_window_in_stacked_widget = QtWidgets.QWidget()
        self.add_book_window_in_stacked_widget.setObjectName("add_book_window_in_stacked_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.add_book_window_in_stacked_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.back_to_main_window_add_book = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.back_to_main_window_add_book.setMaximumSize(QtCore.QSize(150, 16777215))
        self.back_to_main_window_add_book.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_add_book.setObjectName("back_to_main_window_add_book")
        self.gridLayout_5.addWidget(self.back_to_main_window_add_book, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.window_add_book_labelFirstName = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelFirstName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelFirstName.setObjectName("window_add_book_labelFirstName")
        self.gridLayout_4.addWidget(self.window_add_book_labelFirstName, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.window_add_book_middlename = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_middlename.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_book_middlename.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_middlename.setObjectName("window_add_book_middlename")
        self.gridLayout_4.addWidget(self.window_add_book_middlename, 2, 5, 1, 1)
        self.window_add_book_labelMiddleName = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelMiddleName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelMiddleName.setObjectName("window_add_book_labelMiddleName")
        self.gridLayout_4.addWidget(self.window_add_book_labelMiddleName, 2, 4, 1, 1)
        self.window_add_book_labelAuthor = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelAuthor.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelAuthor.setObjectName("window_add_book_labelAuthor")
        self.gridLayout_4.addWidget(self.window_add_book_labelAuthor, 2, 6, 1, 1)
        self.window_add_book_labelLastName = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelLastName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelLastName.setObjectName("window_add_book_labelLastName")
        self.gridLayout_4.addWidget(self.window_add_book_labelLastName, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.window_add_book_lastname = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_lastname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_book_lastname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_lastname.setObjectName("window_add_book_lastname")
        self.gridLayout_4.addWidget(self.window_add_book_lastname, 2, 1, 1, 1)
        self.window_add_book_labelName = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelName.setObjectName("window_add_book_labelName")
        self.gridLayout_4.addWidget(self.window_add_book_labelName, 0, 4, 1, 1)
        self.window_add_book_name_book = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_name_book.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_book_name_book.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_name_book.setObjectName("window_add_book_name_book")
        self.gridLayout_4.addWidget(self.window_add_book_name_book, 0, 3, 1, 1)
        self.window_add_book_year = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_year.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_book_year.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_year.setObjectName("window_add_book_year")
        self.gridLayout_4.addWidget(self.window_add_book_year, 1, 3, 1, 1)
        self.window_add_book_labelYear = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelYear.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelYear.setObjectName("window_add_book_labelYear")
        self.gridLayout_4.addWidget(self.window_add_book_labelYear, 1, 4, 1, 1)
        self.window_add_book_treeWidget = QtWidgets.QTreeWidget(self.add_book_window_in_stacked_widget)
        self.window_add_book_treeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_book_treeWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.window_add_book_treeWidget.setObjectName("window_add_book_treeWidget")
        self.window_add_book_treeWidget.headerItem().setText(0, "1")
        self.gridLayout_4.addWidget(self.window_add_book_treeWidget, 11, 3, 1, 1)
        self.window_add_book_btn_add = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.window_add_book_btn_add.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.window_add_book_btn_add.setObjectName("window_add_book_btn_add")
        self.gridLayout_4.addWidget(self.window_add_book_btn_add, 14, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_add_book_nickname = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_nickname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_nickname.setObjectName("window_add_book_nickname")
        self.gridLayout_4.addWidget(self.window_add_book_nickname, 3, 4, 1, 1)
        self.window_add_book_nikname = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_nikname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_book_nikname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_nikname.setObjectName("window_add_book_nikname")
        self.gridLayout_4.addWidget(self.window_add_book_nikname, 3, 3, 1, 1)
        self.window_add_book_btn_choose = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.window_add_book_btn_choose.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.window_add_book_btn_choose.setBaseSize(QtCore.QSize(150, 0))
        self.window_add_book_btn_choose.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 35 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 5px;\n"
"padding: 3px;")
        self.window_add_book_btn_choose.setObjectName("window_add_book_btn_choose")
        self.gridLayout_4.addWidget(self.window_add_book_btn_choose, 6, 4, 1, 1)
        self.window_add_book_labelTags = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelTags.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelTags.setObjectName("window_add_book_labelTags")
        self.gridLayout_4.addWidget(self.window_add_book_labelTags, 8, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_add_book_labelPath = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.window_add_book_labelPath.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_book_labelPath.setObjectName("window_add_book_labelPath")
        self.gridLayout_4.addWidget(self.window_add_book_labelPath, 6, 5, 1, 1)
        self.window_add_file_path = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_file_path.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.window_add_file_path.sizePolicy().hasHeightForWidth())
        self.window_add_file_path.setSizePolicy(sizePolicy)
        self.window_add_file_path.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_file_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_file_path.setObjectName("window_add_file_path")
        self.gridLayout_4.addWidget(self.window_add_file_path, 6, 3, 1, 1)
        self.window_add_book_firstname = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_firstname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_book_firstname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_firstname.setObjectName("window_add_book_firstname")
        self.gridLayout_4.addWidget(self.window_add_book_firstname, 2, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.add_book_window_in_stacked_widget)
        self.edit_window_in_stacked_widget = QtWidgets.QWidget()
        self.edit_window_in_stacked_widget.setObjectName("edit_window_in_stacked_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.edit_window_in_stacked_widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.back_to_main_window_edit_book = QtWidgets.QPushButton(self.edit_window_in_stacked_widget)
        self.back_to_main_window_edit_book.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_edit_book.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_edit_book.setObjectName("back_to_main_window_edit_book")
        self.gridLayout_7.addWidget(self.back_to_main_window_edit_book, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.window_edit_book_treeWidget = QtWidgets.QTreeWidget(self.edit_window_in_stacked_widget)
        self.window_edit_book_treeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.window_edit_book_treeWidget.setMaximumSize(QtCore.QSize(16777214, 16777214))
        self.window_edit_book_treeWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.window_edit_book_treeWidget.setObjectName("window_edit_book_treeWidget")
        self.window_edit_book_treeWidget.headerItem().setText(0, "1")
        self.gridLayout_6.addWidget(self.window_edit_book_treeWidget, 26, 3, 1, 1)
        self.window_edit_book_middlename = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_middlename.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_middlename.setObjectName("window_edit_book_middlename")
        self.gridLayout_6.addWidget(self.window_edit_book_middlename, 13, 5, 1, 1)
        self.window_edit_book_labelLastName = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelLastName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelLastName.setObjectName("window_edit_book_labelLastName")
        self.gridLayout_6.addWidget(self.window_edit_book_labelLastName, 13, 0, 1, 1, QtCore.Qt.AlignRight)
        self.window_edit_book_labelFirstName = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelFirstName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelFirstName.setObjectName("window_edit_book_labelFirstName")
        self.gridLayout_6.addWidget(self.window_edit_book_labelFirstName, 13, 2, 1, 1, QtCore.Qt.AlignRight)
        self.window_edit_book_labelAuthor = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelAuthor.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelAuthor.setObjectName("window_edit_book_labelAuthor")
        self.gridLayout_6.addWidget(self.window_edit_book_labelAuthor, 13, 6, 1, 1)
        self.window_edit_book_labelMiddleName = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelMiddleName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelMiddleName.setObjectName("window_edit_book_labelMiddleName")
        self.gridLayout_6.addWidget(self.window_edit_book_labelMiddleName, 13, 4, 1, 1)
        self.window_edit_book_labelName = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelName.setObjectName("window_edit_book_labelName")
        self.gridLayout_6.addWidget(self.window_edit_book_labelName, 1, 4, 1, 1)
        self.window_edit_book_labelYear = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelYear.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelYear.setWordWrap(False)
        self.window_edit_book_labelYear.setObjectName("window_edit_book_labelYear")
        self.gridLayout_6.addWidget(self.window_edit_book_labelYear, 3, 4, 1, 1)
        self.window_edit_book_labelNickname = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelNickname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelNickname.setObjectName("window_edit_book_labelNickname")
        self.gridLayout_6.addWidget(self.window_edit_book_labelNickname, 22, 4, 1, 1)
        self.window_edit_book_year = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_year.setMinimumSize(QtCore.QSize(400, 0))
        self.window_edit_book_year.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_year.setObjectName("window_edit_book_year")
        self.gridLayout_6.addWidget(self.window_edit_book_year, 3, 3, 1, 1)
        self.window_edit_book_name_book = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_name_book.setMinimumSize(QtCore.QSize(400, 0))
        self.window_edit_book_name_book.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_name_book.setObjectName("window_edit_book_name_book")
        self.gridLayout_6.addWidget(self.window_edit_book_name_book, 1, 3, 1, 1)
        self.window_edit_book_nickname = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_nickname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_edit_book_nickname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_nickname.setObjectName("window_edit_book_nickname")
        self.gridLayout_6.addWidget(self.window_edit_book_nickname, 22, 3, 1, 1)
        self.window_edit_book_lastname = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_lastname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_lastname.setObjectName("window_edit_book_lastname")
        self.gridLayout_6.addWidget(self.window_edit_book_lastname, 13, 1, 1, 1)
        self.window_edit_book_btn_edit = QtWidgets.QPushButton(self.edit_window_in_stacked_widget)
        self.window_edit_book_btn_edit.setMinimumSize(QtCore.QSize(150, 0))
        self.window_edit_book_btn_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.window_edit_book_btn_edit.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.window_edit_book_btn_edit.setObjectName("window_edit_book_btn_edit")
        self.gridLayout_6.addWidget(self.window_edit_book_btn_edit, 27, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_edit_book_firstname = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_firstname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_edit_book_firstname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_firstname.setObjectName("window_edit_book_firstname")
        self.gridLayout_6.addWidget(self.window_edit_book_firstname, 13, 3, 1, 1)
        self.window_edit_book_labelTags = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.window_edit_book_labelTags.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_edit_book_labelTags.setObjectName("window_edit_book_labelTags")
        self.gridLayout_6.addWidget(self.window_edit_book_labelTags, 23, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.edit_window_in_stacked_widget)
        self.delete_window_in_stacked_widget = QtWidgets.QWidget()
        self.delete_window_in_stacked_widget.setObjectName("delete_window_in_stacked_widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.delete_window_in_stacked_widget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.window_search_book_btn_search = QtWidgets.QPushButton(self.delete_window_in_stacked_widget)
        self.window_search_book_btn_search.setMinimumSize(QtCore.QSize(150, 0))
        self.window_search_book_btn_search.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.window_search_book_btn_search.setObjectName("window_search_book_btn_search")
        self.gridLayout_8.addWidget(self.window_search_book_btn_search, 8, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_search_book_lastname = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_lastname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_search_book_lastname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_book_lastname.setObjectName("window_search_book_lastname")
        self.gridLayout_8.addWidget(self.window_search_book_lastname, 2, 1, 1, 1)
        self.window_search_book_labelName = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelName.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelName.setObjectName("window_search_book_labelName")
        self.gridLayout_8.addWidget(self.window_search_book_labelName, 0, 4, 1, 1)
        self.window_search_book_year = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_year.setMinimumSize(QtCore.QSize(400, 0))
        self.window_search_book_year.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_book_year.setObjectName("window_search_book_year")
        self.gridLayout_8.addWidget(self.window_search_book_year, 1, 3, 1, 1)
        self.window_search_book_labelYear = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelYear.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelYear.setObjectName("window_search_book_labelYear")
        self.gridLayout_8.addWidget(self.window_search_book_labelYear, 1, 4, 1, 1)
        self.window_search_book_treeWidget = QtWidgets.QTreeWidget(self.delete_window_in_stacked_widget)
        self.window_search_book_treeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.window_search_book_treeWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.window_search_book_treeWidget.setObjectName("window_search_book_treeWidget")
        self.window_search_book_treeWidget.headerItem().setText(0, "1")
        self.gridLayout_8.addWidget(self.window_search_book_treeWidget, 6, 3, 1, 1)
        self.window_search_book_name_book = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_name_book.setMinimumSize(QtCore.QSize(400, 0))
        self.window_search_book_name_book.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_book_name_book.setObjectName("window_search_book_name_book")
        self.gridLayout_8.addWidget(self.window_search_book_name_book, 0, 3, 1, 1)
        self.window_search_book_labelFirstname = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelFirstname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelFirstname.setObjectName("window_search_book_labelFirstname")
        self.gridLayout_8.addWidget(self.window_search_book_labelFirstname, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.window_search_book_firstname = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_firstname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_search_book_firstname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_book_firstname.setObjectName("window_search_book_firstname")
        self.gridLayout_8.addWidget(self.window_search_book_firstname, 2, 3, 1, 1)
        self.window_search_book_labelLastname = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelLastname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelLastname.setObjectName("window_search_book_labelLastname")
        self.gridLayout_8.addWidget(self.window_search_book_labelLastname, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.window_search_book_middlename = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_middlename.setMinimumSize(QtCore.QSize(400, 0))
        self.window_search_book_middlename.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_book_middlename.setObjectName("window_search_book_middlename")
        self.gridLayout_8.addWidget(self.window_search_book_middlename, 2, 5, 1, 1)
        self.window_search_book_labelMiddlename = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelMiddlename.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelMiddlename.setObjectName("window_search_book_labelMiddlename")
        self.gridLayout_8.addWidget(self.window_search_book_labelMiddlename, 2, 4, 1, 1)
        self.window_search_book_labelTags = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelTags.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelTags.setObjectName("window_search_book_labelTags")
        self.gridLayout_8.addWidget(self.window_search_book_labelTags, 5, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_search_book_labelAuthor = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelAuthor.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelAuthor.setObjectName("window_search_book_labelAuthor")
        self.gridLayout_8.addWidget(self.window_search_book_labelAuthor, 2, 6, 1, 1)
        self.window_search_book_nickname = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_nickname.setMinimumSize(QtCore.QSize(400, 0))
        self.window_search_book_nickname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_book_nickname.setObjectName("window_search_book_nickname")
        self.gridLayout_8.addWidget(self.window_search_book_nickname, 3, 3, 1, 1)
        self.window_search_book_labelNickname = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.window_search_book_labelNickname.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_search_book_labelNickname.setObjectName("window_search_book_labelNickname")
        self.gridLayout_8.addWidget(self.window_search_book_labelNickname, 3, 4, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.back_to_main_window_search_book = QtWidgets.QPushButton(self.delete_window_in_stacked_widget)
        self.back_to_main_window_search_book.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_search_book.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_search_book.setObjectName("back_to_main_window_search_book")
        self.gridLayout_11.addWidget(self.back_to_main_window_search_book, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.stackedWidget.addWidget(self.delete_window_in_stacked_widget)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.back_to_main_window_delete_tag = QtWidgets.QPushButton(self.page)
        self.back_to_main_window_delete_tag.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_delete_tag.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_delete_tag.setObjectName("back_to_main_window_delete_tag")
        self.gridLayout_12.addWidget(self.back_to_main_window_delete_tag, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.window_delete_tag_treeWidget = QtWidgets.QTreeWidget(self.page)
        self.window_delete_tag_treeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.window_delete_tag_treeWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.window_delete_tag_treeWidget.setObjectName("window_delete_tag_treeWidget")
        self.window_delete_tag_treeWidget.headerItem().setText(0, "1")
        self.gridLayout_10.addWidget(self.window_delete_tag_treeWidget, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_delete_tag_btn_delete = QtWidgets.QPushButton(self.page)
        self.window_delete_tag_btn_delete.setMinimumSize(QtCore.QSize(150, 0))
        self.window_delete_tag_btn_delete.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.window_delete_tag_btn_delete.setObjectName("window_delete_tag_btn_delete")
        self.gridLayout_10.addWidget(self.window_delete_tag_btn_delete, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_delete_tag_labelTags = QtWidgets.QLabel(self.page)
        self.window_delete_tag_labelTags.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_delete_tag_labelTags.setObjectName("window_delete_tag_labelTags")
        self.gridLayout_10.addWidget(self.window_delete_tag_labelTags, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_12.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.search_window_in_stacked_widget = QtWidgets.QWidget()
        self.search_window_in_stacked_widget.setObjectName("search_window_in_stacked_widget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.search_window_in_stacked_widget)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.back_to_main_window_add_tag = QtWidgets.QPushButton(self.search_window_in_stacked_widget)
        self.back_to_main_window_add_tag.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_add_tag.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_add_tag.setObjectName("back_to_main_window_add_tag")
        self.gridLayout_13.addWidget(self.back_to_main_window_add_tag, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.window_add_tag_labelTags = QtWidgets.QLabel(self.search_window_in_stacked_widget)
        self.window_add_tag_labelTags.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_tag_labelTags.setObjectName("window_add_tag_labelTags")
        self.gridLayout_9.addWidget(self.window_add_tag_labelTags, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 5, 3, 1, 1)
        self.window_add_tag_btn_add = QtWidgets.QPushButton(self.search_window_in_stacked_widget)
        self.window_add_tag_btn_add.setMinimumSize(QtCore.QSize(150, 0))
        self.window_add_tag_btn_add.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.window_add_tag_btn_add.setObjectName("window_add_tag_btn_add")
        self.gridLayout_9.addWidget(self.window_add_tag_btn_add, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.window_add_tag_labelNametag = QtWidgets.QLabel(self.search_window_in_stacked_widget)
        self.window_add_tag_labelNametag.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.window_add_tag_labelNametag.setObjectName("window_add_tag_labelNametag")
        self.gridLayout_9.addWidget(self.window_add_tag_labelNametag, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.window_add_tag_name_tag = QtWidgets.QLineEdit(self.search_window_in_stacked_widget)
        self.window_add_tag_name_tag.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_tag_name_tag.setMaximumSize(QtCore.QSize(16665731, 16777215))
        self.window_add_tag_name_tag.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_tag_name_tag.setObjectName("window_add_tag_name_tag")
        self.gridLayout_9.addWidget(self.window_add_tag_name_tag, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 5, 1, 1, 1)
        self.window_add_tag_treeView = QtWidgets.QTreeView(self.search_window_in_stacked_widget)
        self.window_add_tag_treeView.setMinimumSize(QtCore.QSize(400, 0))
        self.window_add_tag_treeView.setMaximumSize(QtCore.QSize(16632343, 16777215))
        self.window_add_tag_treeView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.window_add_tag_treeView.setObjectName("window_add_tag_treeView")
        self.gridLayout_9.addWidget(self.window_add_tag_treeView, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_13.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_window_in_stacked_widget)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1685, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.add_book_button, self.search_book_button)
        MainWindow.setTabOrder(self.search_book_button, self.add_category_button)
        MainWindow.setTabOrder(self.add_category_button, self.delete_category_button)
        MainWindow.setTabOrder(self.delete_category_button, self.main_window_tags)
        MainWindow.setTabOrder(self.main_window_tags, self.listWidget)
        MainWindow.setTabOrder(self.listWidget, self.main_window_LineEdit)
        MainWindow.setTabOrder(self.main_window_LineEdit, self.main_window_button)
        MainWindow.setTabOrder(self.main_window_button, self.back_to_main_window_add_book)
        MainWindow.setTabOrder(self.back_to_main_window_add_book, self.window_add_book_name_book)
        MainWindow.setTabOrder(self.window_add_book_name_book, self.window_add_book_year)
        MainWindow.setTabOrder(self.window_add_book_year, self.window_add_book_lastname)
        MainWindow.setTabOrder(self.window_add_book_lastname, self.window_add_book_firstname)
        MainWindow.setTabOrder(self.window_add_book_firstname, self.window_add_book_middlename)
        MainWindow.setTabOrder(self.window_add_book_middlename, self.window_add_book_nikname)
        MainWindow.setTabOrder(self.window_add_book_nikname, self.window_add_file_path)
        MainWindow.setTabOrder(self.window_add_file_path, self.window_add_book_btn_choose)
        MainWindow.setTabOrder(self.window_add_book_btn_choose, self.window_add_book_treeWidget)
        MainWindow.setTabOrder(self.window_add_book_treeWidget, self.window_add_book_btn_add)
        MainWindow.setTabOrder(self.window_add_book_btn_add, self.back_to_main_window_edit_book)
        MainWindow.setTabOrder(self.back_to_main_window_edit_book, self.window_edit_book_name_book)
        MainWindow.setTabOrder(self.window_edit_book_name_book, self.window_edit_book_year)
        MainWindow.setTabOrder(self.window_edit_book_year, self.window_edit_book_lastname)
        MainWindow.setTabOrder(self.window_edit_book_lastname, self.window_edit_book_firstname)
        MainWindow.setTabOrder(self.window_edit_book_firstname, self.window_edit_book_middlename)
        MainWindow.setTabOrder(self.window_edit_book_middlename, self.window_edit_book_nickname)
        MainWindow.setTabOrder(self.window_edit_book_nickname, self.window_edit_book_treeWidget)
        MainWindow.setTabOrder(self.window_edit_book_treeWidget, self.window_edit_book_btn_edit)
        MainWindow.setTabOrder(self.window_edit_book_btn_edit, self.back_to_main_window_search_book)
        MainWindow.setTabOrder(self.back_to_main_window_search_book, self.window_search_book_name_book)
        MainWindow.setTabOrder(self.window_search_book_name_book, self.window_search_book_year)
        MainWindow.setTabOrder(self.window_search_book_year, self.window_search_book_lastname)
        MainWindow.setTabOrder(self.window_search_book_lastname, self.window_search_book_firstname)
        MainWindow.setTabOrder(self.window_search_book_firstname, self.window_search_book_middlename)
        MainWindow.setTabOrder(self.window_search_book_middlename, self.window_search_book_nickname)
        MainWindow.setTabOrder(self.window_search_book_nickname, self.window_search_book_treeWidget)
        MainWindow.setTabOrder(self.window_search_book_treeWidget, self.window_search_book_btn_search)
        MainWindow.setTabOrder(self.window_search_book_btn_search, self.back_to_main_window_delete_tag)
        MainWindow.setTabOrder(self.back_to_main_window_delete_tag, self.window_delete_tag_treeWidget)
        MainWindow.setTabOrder(self.window_delete_tag_treeWidget, self.window_delete_tag_btn_delete)
        MainWindow.setTabOrder(self.window_delete_tag_btn_delete, self.back_to_main_window_add_tag)
        MainWindow.setTabOrder(self.back_to_main_window_add_tag, self.window_add_tag_name_tag)
        MainWindow.setTabOrder(self.window_add_tag_name_tag, self.window_add_tag_treeView)
        MainWindow.setTabOrder(self.window_add_tag_treeView, self.window_add_tag_btn_add)
        MainWindow.setTabOrder(self.window_add_tag_btn_add, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_book_button.setText(_translate("MainWindow", "Добавить книгу"))
        self.search_book_button.setText(_translate("MainWindow", "Найти книгу"))
        self.add_category_button.setText(_translate("MainWindow", "Добавить тег"))
        self.delete_category_button.setText(_translate("MainWindow", "Удалить тег"))
        self.main_window_tags.headerItem().setText(1, _translate("MainWindow", "Книги"))
        __sortingEnabled = self.main_window_tags.isSortingEnabled()
        self.main_window_tags.setSortingEnabled(False)
        self.main_window_tags.topLevelItem(0).setText(0, _translate("MainWindow", "Стандартные"))
        self.main_window_tags.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Жанры"))
        self.main_window_tags.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Антиутопии"))
        self.main_window_tags.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Фантастика"))
        self.main_window_tags.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Авторы"))
        self.main_window_tags.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Год"))
        self.main_window_tags.topLevelItem(1).setText(0, _translate("MainWindow", "Пользовательские"))
        self.main_window_tags.setSortingEnabled(__sortingEnabled)
        self.main_window_button.setText(_translate("MainWindow", "Применить"))
        self.back_to_main_window_add_book.setText(_translate("MainWindow", "На главную"))
        self.window_add_book_labelFirstName.setText(_translate("MainWindow", "Имя:"))
        self.window_add_book_labelMiddleName.setText(_translate("MainWindow", "Отчество:"))
        self.window_add_book_labelAuthor.setText(_translate("MainWindow", "Автор"))
        self.window_add_book_labelLastName.setText(_translate("MainWindow", "Фамилия:"))
        self.window_add_book_labelName.setText(_translate("MainWindow", "Название"))
        self.window_add_book_labelYear.setText(_translate("MainWindow", "Год"))
        self.window_add_book_btn_add.setText(_translate("MainWindow", "Добавить"))
        self.window_add_book_nickname.setText(_translate("MainWindow", "Псевдоним"))
        self.window_add_book_btn_choose.setText(_translate("MainWindow", "Выбрать"))
        self.window_add_book_labelTags.setText(_translate("MainWindow", "Теги"))
        self.window_add_book_labelPath.setText(_translate("MainWindow", "Путь"))
        self.back_to_main_window_edit_book.setText(_translate("MainWindow", "На главную"))
        self.window_edit_book_labelLastName.setText(_translate("MainWindow", "Фамилия:"))
        self.window_edit_book_labelFirstName.setText(_translate("MainWindow", "Имя:"))
        self.window_edit_book_labelAuthor.setText(_translate("MainWindow", "Автор"))
        self.window_edit_book_labelMiddleName.setText(_translate("MainWindow", "Отчество:"))
        self.window_edit_book_labelName.setText(_translate("MainWindow", "Название"))
        self.window_edit_book_labelYear.setText(_translate("MainWindow", "Год"))
        self.window_edit_book_labelNickname.setText(_translate("MainWindow", "Псевдоним"))
        self.window_edit_book_btn_edit.setText(_translate("MainWindow", "Изменить"))
        self.window_edit_book_labelTags.setText(_translate("MainWindow", "Теги"))
        self.window_search_book_btn_search.setText(_translate("MainWindow", "Найти"))
        self.window_search_book_labelName.setText(_translate("MainWindow", "Название"))
        self.window_search_book_labelYear.setText(_translate("MainWindow", "Год"))
        self.window_search_book_labelFirstname.setText(_translate("MainWindow", "Имя:"))
        self.window_search_book_labelLastname.setText(_translate("MainWindow", "Фамилия:"))
        self.window_search_book_labelMiddlename.setText(_translate("MainWindow", "Отчество:"))
        self.window_search_book_labelTags.setText(_translate("MainWindow", "Теги"))
        self.window_search_book_labelAuthor.setText(_translate("MainWindow", "Автор"))
        self.window_search_book_labelNickname.setText(_translate("MainWindow", "Псевдоним"))
        self.back_to_main_window_search_book.setText(_translate("MainWindow", "На главную"))
        self.back_to_main_window_delete_tag.setText(_translate("MainWindow", "На главную"))
        self.window_delete_tag_btn_delete.setText(_translate("MainWindow", "Удалить"))
        self.window_delete_tag_labelTags.setText(_translate("MainWindow", "Выберите теги для удаления:"))
        self.back_to_main_window_add_tag.setText(_translate("MainWindow", "На главную"))
        self.window_add_tag_labelTags.setText(_translate("MainWindow", "Теги"))
        self.window_add_tag_btn_add.setText(_translate("MainWindow", "Добавить тег"))
        self.window_add_tag_labelNametag.setText(_translate("MainWindow", "Название тега:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Приложение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Статистика"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Документация"))
