# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(235, 235, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget.setStyleSheet("background-color: rgb(230, 236, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_window_in_stacked_widget = QtWidgets.QWidget()
        self.main_window_in_stacked_widget.setObjectName("main_window_in_stacked_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_window_in_stacked_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_book_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.add_book_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.add_book_button.setObjectName("add_book_button")
        self.horizontalLayout_2.addWidget(self.add_book_button)
        self.search_book_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.search_book_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.search_book_button.setObjectName("search_book_button")
        self.horizontalLayout_2.addWidget(self.search_book_button)
        self.add_category_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.add_category_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.add_category_button.setObjectName("add_category_button")
        self.horizontalLayout_2.addWidget(self.add_category_button)
        self.delete_category_button = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.delete_category_button.setStyleSheet("background-color: rgb(111, 125, 255);\n"
"background-color: rgb(116, 106, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 5px 5px 5px;\n"
"margin: 5px 5px 5px 5px;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.delete_category_button.setObjectName("delete_category_button")
        self.horizontalLayout_2.addWidget(self.delete_category_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.treeWidget = QtWidgets.QTreeWidget(self.main_window_in_stacked_widget)
        self.treeWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.treeWidget.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Категории")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout_24.addWidget(self.treeWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.main_window_in_stacked_widget)
        self.listWidget.setMinimumSize(QtCore.QSize(900, 0))
        self.listWidget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(116, 106, 255);\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.main_window_in_stacked_widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(600, 0))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border: 4px solid rgb(116, 106, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.main_window_in_stacked_widget)
        self.pushButton.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_24.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_window_in_stacked_widget)
        self.add_book_window_in_stacked_widget = QtWidgets.QWidget()
        self.add_book_window_in_stacked_widget.setObjectName("add_book_window_in_stacked_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.add_book_window_in_stacked_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.back_to_main_window_add_book = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.back_to_main_window_add_book.setMaximumSize(QtCore.QSize(150, 16777215))
        self.back_to_main_window_add_book.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_add_book.setObjectName("back_to_main_window_add_book")
        self.gridLayout_5.addWidget(self.back_to_main_window_add_book, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.add_book_window_in_stacked_widget)
        self.treeWidget_2.setMinimumSize(QtCore.QSize(470, 0))
        self.treeWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.treeWidget_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(350, 0))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem7)
        self.gridLayout_4.addLayout(self.horizontalLayout_29, 0, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(410, 0))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.horizontalLayout_28, 1, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.window_add_file_path = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_file_path.setMinimumSize(QtCore.QSize(250, 0))
        self.window_add_file_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_file_path.setObjectName("window_add_file_path")
        self.horizontalLayout_6.addWidget(self.window_add_file_path)
        self.label_8 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_8.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.pushButton_2.setBaseSize(QtCore.QSize(150, 0))
        self.pushButton_2.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 35 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 5px;\n"
"padding: 3px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem11)
        self.gridLayout_4.addLayout(self.horizontalLayout_27, 4, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.window_add_book_lastname = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_lastname.setMinimumSize(QtCore.QSize(0, 0))
        self.window_add_book_lastname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_lastname.setObjectName("window_add_book_lastname")
        self.horizontalLayout_5.addWidget(self.window_add_book_lastname)
        self.label_18 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_18.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_5.addWidget(self.label_18)
        self.window_add_book_firstname = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_firstname.setMinimumSize(QtCore.QSize(0, 0))
        self.window_add_book_firstname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_firstname.setObjectName("window_add_book_firstname")
        self.horizontalLayout_5.addWidget(self.window_add_book_firstname)
        self.label_19 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_19.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.window_add_book_middlename = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_middlename.setMinimumSize(QtCore.QSize(0, 0))
        self.window_add_book_middlename.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_middlename.setObjectName("window_add_book_middlename")
        self.horizontalLayout_5.addWidget(self.window_add_book_middlename)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_5)
        self.label_20 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_20.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_25.addWidget(self.label_20)
        self.gridLayout_4.addLayout(self.horizontalLayout_25, 2, 0, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem12)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.window_add_book_nikname = QtWidgets.QLineEdit(self.add_book_window_in_stacked_widget)
        self.window_add_book_nikname.setMinimumSize(QtCore.QSize(330, 0))
        self.window_add_book_nikname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_add_book_nikname.setObjectName("window_add_book_nikname")
        self.horizontalLayout_30.addWidget(self.window_add_book_nikname)
        self.label_21 = QtWidgets.QLabel(self.add_book_window_in_stacked_widget)
        self.label_21.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_30.addWidget(self.label_21)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem13)
        self.gridLayout_4.addLayout(self.horizontalLayout_31, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.pushButton_3 = QtWidgets.QPushButton(self.add_book_window_in_stacked_widget)
        self.pushButton_3.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 4, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 524, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem16, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 2, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(183, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.add_book_window_in_stacked_widget)
        self.edit_window_in_stacked_widget = QtWidgets.QWidget()
        self.edit_window_in_stacked_widget.setObjectName("edit_window_in_stacked_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.edit_window_in_stacked_widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.back_to_main_window_edit_book = QtWidgets.QPushButton(self.edit_window_in_stacked_widget)
        self.back_to_main_window_edit_book.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_edit_book.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_edit_book.setObjectName("back_to_main_window_edit_book")
        self.gridLayout_7.addWidget(self.back_to_main_window_edit_book, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem19, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem20)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(350, 0))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        self.label_2 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_9)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem21)
        self.gridLayout_6.addLayout(self.horizontalLayout_36, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_22.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.window_edit_book_firstname = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_firstname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_firstname.setObjectName("window_edit_book_firstname")
        self.horizontalLayout_10.addWidget(self.window_edit_book_firstname)
        self.label_23 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_23.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.window_edit_book_lastname = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_lastname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_lastname.setObjectName("window_edit_book_lastname")
        self.horizontalLayout_10.addWidget(self.window_edit_book_lastname)
        self.label_24 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_24.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.window_edit_book_middlename = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_middlename.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_middlename.setObjectName("window_edit_book_middlename")
        self.horizontalLayout_10.addWidget(self.window_edit_book_middlename)
        self.label_10 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem22)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.window_edit_book_nikname = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.window_edit_book_nikname.setMinimumSize(QtCore.QSize(340, 0))
        self.window_edit_book_nikname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_edit_book_nikname.setObjectName("window_edit_book_nikname")
        self.horizontalLayout_32.addWidget(self.window_edit_book_nikname)
        self.label_25 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_25.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_32.addWidget(self.label_25)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_32)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem23)
        self.gridLayout_6.addLayout(self.horizontalLayout_35, 2, 0, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem24)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.edit_window_in_stacked_widget)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(410, 0))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_11.addWidget(self.lineEdit_8)
        self.label_11 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_11)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem25)
        self.gridLayout_6.addLayout(self.horizontalLayout_34, 3, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem26)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.edit_window_in_stacked_widget)
        self.label_12.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.edit_window_in_stacked_widget)
        self.treeWidget_3.setMinimumSize(QtCore.QSize(470, 0))
        self.treeWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.treeWidget_3.headerItem().setText(0, "1")
        self.verticalLayout_3.addWidget(self.treeWidget_3)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem27)
        self.gridLayout_6.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem28)
        self.pushButton_4 = QtWidgets.QPushButton(self.edit_window_in_stacked_widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_4.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_13.addWidget(self.pushButton_4)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem29)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 1, 3, 1)
        spacerItem30 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem30, 2, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem31, 3, 2, 1, 1)
        self.stackedWidget.addWidget(self.edit_window_in_stacked_widget)
        self.delete_window_in_stacked_widget = QtWidgets.QWidget()
        self.delete_window_in_stacked_widget.setObjectName("delete_window_in_stacked_widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.delete_window_in_stacked_widget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.back_to_main_window_search_bok = QtWidgets.QPushButton(self.delete_window_in_stacked_widget)
        self.back_to_main_window_search_bok.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_search_bok.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_search_bok.setObjectName("back_to_main_window_search_bok")
        self.gridLayout_11.addWidget(self.back_to_main_window_search_bok, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem32)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")

        self.window_search_name_book = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_name_book.setMinimumSize(QtCore.QSize(350, 0))
        self.window_search_name_book.setStyleSheet("background-color: rgb(255, 255, 255);\n")

        self.window_search_book_name = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")

        self.window_search_name_book.setObjectName("window_search_name_book")
        self.horizontalLayout_14.addWidget(self.window_search_name_book)

        self.window_search_book_name.setObjectName("lineEdit_9")
        self.horizontalLayout_14.addWidget(self.window_search_book_name)

        self.label_3 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_14)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem33)
        self.gridLayout_8.addLayout(self.horizontalLayout_38, 0, 0, 1, 1)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_26 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_26.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_37.addWidget(self.label_26)
        self.window_search_first_name = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_first_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_first_name.setObjectName("window_search_first_name")
        self.horizontalLayout_37.addWidget(self.window_search_first_name)
        self.label_27 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_27.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_37.addWidget(self.label_27)
        self.window_search_last_name = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_last_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_last_name.setObjectName("window_search_last_name")
        self.horizontalLayout_37.addWidget(self.window_search_last_name)
        self.label_28 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_28.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_37.addWidget(self.label_28)
        self.window_search_middle_name = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_middle_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_middle_name.setObjectName("window_search_middle_name")
        self.horizontalLayout_37.addWidget(self.window_search_middle_name)
        self.label_13 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_13.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")

        self.horizontalLayout_37.addWidget(self.label_13)
        self.gridLayout_8.addLayout(self.horizontalLayout_37, 1, 0, 1, 1)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem34)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.window_search_nikname = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_nikname.setMinimumSize(QtCore.QSize(340, 0))
        self.window_search_nikname.setStyleSheet("background-color: rgb(255, 255, 255);\n")

        self.horizontalLayout_15.addWidget(self.label_13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.window_search_book_year = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_book_year.setStyleSheet("background-color: rgb(255, 255, 255);\n"

"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")

        self.window_search_nikname.setObjectName("window_search_nikname")
        self.horizontalLayout_15.addWidget(self.window_search_nikname)
        self.label_29 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_29.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_15)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem35)
        self.gridLayout_8.addLayout(self.horizontalLayout_39, 2, 0, 1, 1)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem36)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.window_search_year = QtWidgets.QLineEdit(self.delete_window_in_stacked_widget)
        self.window_search_year.setMinimumSize(QtCore.QSize(410, 0))
        self.window_search_year.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.window_search_year.setObjectName("window_search_year")
        self.horizontalLayout_16.addWidget(self.window_search_year)

        self.window_search_book_year.setObjectName("lineEdit_11")
        self.horizontalLayout_16.addWidget(self.window_search_book_year)

        self.label_14 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_14.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.horizontalLayout_40.addLayout(self.horizontalLayout_16)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem37)
        self.gridLayout_8.addLayout(self.horizontalLayout_40, 3, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem38)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.delete_window_in_stacked_widget)
        self.label_15.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.delete_window_in_stacked_widget)
        self.treeWidget_4.setMinimumSize(QtCore.QSize(450, 0))
        self.treeWidget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_4.setObjectName("treeWidget_4")
        self.treeWidget_4.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.treeWidget_4)
        self.horizontalLayout_17.addLayout(self.verticalLayout_4)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem39)
        self.gridLayout_8.addLayout(self.horizontalLayout_17, 4, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem40)
        self.pushButton_5 = QtWidgets.QPushButton(self.delete_window_in_stacked_widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_5.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_18.addWidget(self.pushButton_5)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem41)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 5, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_8, 0, 1, 3, 1)
        spacerItem42 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem42, 1, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(193, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem43, 2, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem44, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.delete_window_in_stacked_widget)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.back_to_main_window_delete_category = QtWidgets.QPushButton(self.page)
        self.back_to_main_window_delete_category.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_delete_category.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_delete_category.setObjectName("back_to_main_window_delete_category")
        self.gridLayout_10.addWidget(self.back_to_main_window_delete_category, 0, 0, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem45, 1, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.treeWidget_5 = QtWidgets.QTreeWidget(self.page)
        self.treeWidget_5.setMinimumSize(QtCore.QSize(450, 0))
        self.treeWidget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget_5.setObjectName("treeWidget_5")
        self.treeWidget_5.headerItem().setText(0, "1")
        self.horizontalLayout_22.addWidget(self.treeWidget_5)
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem46)
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_8.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_23.addWidget(self.pushButton_8)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem47)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.gridLayout_10.addLayout(self.verticalLayout_7, 1, 2, 2, 1)
        spacerItem48 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem48, 2, 1, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem49, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.search_window_in_stacked_widget = QtWidgets.QWidget()
        self.search_window_in_stacked_widget.setObjectName("search_window_in_stacked_widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.search_window_in_stacked_widget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.back_to_main_window_add_category = QtWidgets.QPushButton(self.search_window_in_stacked_widget)
        self.back_to_main_window_add_category.setMinimumSize(QtCore.QSize(150, 0))
        self.back_to_main_window_add_category.setStyleSheet("background-color: rgb(255, 11, 68);\n"
"color: white;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 7px;")
        self.back_to_main_window_add_category.setObjectName("back_to_main_window_add_category")
        self.gridLayout_9.addWidget(self.back_to_main_window_add_category, 0, 0, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(20, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem50, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.search_window_in_stacked_widget)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"font: 55 12pt \"MS Shell Dlg 2\";\n"
"border: 3px solid rgb(99, 47, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_20.addWidget(self.lineEdit_12)
        self.label_4 = QtWidgets.QLabel(self.search_window_in_stacked_widget)
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_20.addWidget(self.label_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.treeView = QtWidgets.QTreeView(self.search_window_in_stacked_widget)
        self.treeView.setMinimumSize(QtCore.QSize(450, 0))
        self.treeView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_21.addWidget(self.treeView)
        self.label_16 = QtWidgets.QLabel(self.search_window_in_stacked_widget)
        self.label_16.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_21.addWidget(self.label_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem51)
        self.pushButton_6 = QtWidgets.QPushButton(self.search_window_in_stacked_widget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_6.setStyleSheet("background-color: rgb(80, 64, 255);\n"
"color: white;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_19.addWidget(self.pushButton_6)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem52)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.gridLayout_9.addLayout(self.verticalLayout_6, 1, 2, 2, 1)
        spacerItem53 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem53, 2, 1, 1, 1)
        spacerItem54 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem54, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.search_window_in_stacked_widget)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1347, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_book_button.setText(_translate("MainWindow", "Добавить книгу"))
        self.search_book_button.setText(_translate("MainWindow", "Найти книгу"))
        self.add_category_button.setText(_translate("MainWindow", "Добавить категорию"))
        self.delete_category_button.setText(_translate("MainWindow", "Удалить категорию"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Книги"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Стандартные"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Жанры"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Антиутопии"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Фантастика"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Авторы"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Год"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Пользовательские"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Применить"))
        self.back_to_main_window_add_book.setText(_translate("MainWindow", "На главную"))
        self.label_9.setText(_translate("MainWindow", "Категории"))
        self.label_5.setText(_translate("MainWindow", "Название"))
        self.label_6.setText(_translate("MainWindow", "Год"))
        self.label_8.setText(_translate("MainWindow", "Путь"))
        self.pushButton_2.setText(_translate("MainWindow", "Выбрать путь"))
        self.label_7.setText(_translate("MainWindow", "Фамилия :"))
        self.label_18.setText(_translate("MainWindow", "Имя :"))
        self.label_19.setText(_translate("MainWindow", "Отчество :"))
        self.label_20.setText(_translate("MainWindow", "Автор"))
        self.label_21.setText(_translate("MainWindow", "Псевдоним"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.back_to_main_window_edit_book.setText(_translate("MainWindow", "На главную"))
        self.label_2.setText(_translate("MainWindow", "Название"))
        self.label_22.setText(_translate("MainWindow", "Фамилия:"))
        self.label_23.setText(_translate("MainWindow", "Имя:"))
        self.label_24.setText(_translate("MainWindow", "Отчество:"))
        self.label_10.setText(_translate("MainWindow", "Автор"))
        self.label_25.setText(_translate("MainWindow", "Псевдоним"))
        self.label_11.setText(_translate("MainWindow", "Год"))
        self.label_12.setText(_translate("MainWindow", "Категории"))
        self.pushButton_4.setText(_translate("MainWindow", "Изменить"))
        self.back_to_main_window_search_bok.setText(_translate("MainWindow", "На главную"))
        self.label_3.setText(_translate("MainWindow", "Название"))
        self.label_26.setText(_translate("MainWindow", "Фамилия:"))
        self.label_27.setText(_translate("MainWindow", "Имя:"))
        self.label_28.setText(_translate("MainWindow", "Отчество:"))
        self.label_13.setText(_translate("MainWindow", "Автор"))
        self.label_29.setText(_translate("MainWindow", "Псевдоним"))
        self.label_14.setText(_translate("MainWindow", "Год"))
        self.label_15.setText(_translate("MainWindow", "Катогории"))
        self.pushButton_5.setText(_translate("MainWindow", "Найти"))
        self.back_to_main_window_delete_category.setText(_translate("MainWindow", "На главную"))
        self.label_17.setText(_translate("MainWindow", "Категории"))
        self.pushButton_8.setText(_translate("MainWindow", "Удалить"))
        self.back_to_main_window_add_category.setText(_translate("MainWindow", "На главную"))
        self.label_4.setText(_translate("MainWindow", "Название категориии"))
        self.label_16.setText(_translate("MainWindow", "Категории"))
        self.pushButton_6.setText(_translate("MainWindow", "Добавить категорию"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Приложение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Статистика"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Документация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
